[global/wm]
; Adjust the _NET_WM_STRUT_PARTIAL top value
;   Used for top aligned bars
; Supports any percentage with offset relative to the monitor height
margin-bottom = 0

[bar/barre]
height = 20
bottom = true
; Background ARGB color (e.g. #f00, #ff992a, #ddff1023)
background = #808
foreground = #fff

modules-right = date

[module/date]
type = internal/date

; Seconds to sleep between updates
; Default: 1.0
interval = 1.0

; See "https://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = %Y-%m-%d%

; Optional time format
time = %H:%M:%S

# ; if `date-alt` or `time-alt` is defined, clicking
# ; the module will toggle between formats
# date-alt = %A, %d %B %Y
# time-alt = %H:%M:%S
